name: procaffeination
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23877410986460745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#c9b7b4'
    - '#5c5867'
    - '#d77663'
    - '#ff0010'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
