name: procaffeination
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23877410986460745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#969696'
    - '#213a52'
    - '#00b8ba'
    - '#ffb86e'
    - '#ffefa0'
  brandStrength: 0.0625
  lightness: 0.7607457637786865
  saturation: 0.05814925045706332
  rhythmicContrast: 0.5309977552387863
purpose: []
